services:
  photo-processor:
    build: .
    container_name: film-roll-processor
    ports:
      - "3683:3683"
    environment:
      - FLASK_ENV=production
      - OUTPUT_FOLDER=/output
    restart: unless-stopped
    volumes:
      - C:/Users/willr/Pictures/output:/output:rw
    mem_limit: 8g
    cpus: 10